import pandas as pd
import numpy as np
import pickle


teams = [{'TEAM': '$\\alpha$',
  'JUDGE': 'Саша Абанов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\beta$',
  'JUDGE': 'Коля Лужков',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\gamma$',
  'JUDGE': 'Лиза Ефимова',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\delta$',
  'JUDGE': 'Вова Краснобаев',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\varepsilon$',
  'JUDGE': 'Макс Бекетов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\theta$',
  'JUDGE': 'Соня Абанова',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\iota$',
  'JUDGE': 'Таня Гусева',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\pi$',
  'JUDGE': 'Лера Убакова',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\lambda$',
  'JUDGE': 'Катя Семёнова',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\kappa$',
  'JUDGE': 'Лёша Смолянинов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\eta$',
  'JUDGE': 'Саша Менщиков',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$o$',
  'JUDGE': 'Никита Равчеев',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\chi$',
  'JUDGE': 'Ваня Адо',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\mu$',
  'JUDGE': 'Михаил Садовский',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\psi$',
  'JUDGE': 'Борис Демешев',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\tau$',
  'JUDGE': 'Илья Сергеев',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\rho$',
  'JUDGE': 'Антон Шейкин',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\omega$',
  'JUDGE': 'Лев Каминский',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\varphi$',
  'JUDGE': 'Антон Лысенко',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\sigma$',
  'JUDGE': 'Витя Антипов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\xi$',
  'JUDGE': 'Витя Антипов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\nu$',
  'JUDGE': 'Витя Антипов',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\zeta$',
  'JUDGE': 'NNN',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]},
 {'TEAM': '$\\upsilon$',
  'JUDGE': 'MMM',
  'SCORES': [(None, 0), (None, 0), (None, 0), (None, 0)]}]

with open('svalka.pkl', 'wb') as svalka_file:
    pickle.dump(teams, svalka_file)